### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Harvey13** [SketchUp/sketchup-ruby-debugger#12]
Hello
I tried with **SketchUp Make 2017** : SketchUp  opens but remains frozen.
I used SketchUp.exe -rdebug "ide port=7000" with noo wait parameter.

**Comment by BugraB** [comment]
Hi, we haven't yet built the latest changes and made the DLLs available as a new release. The "wait" parameter is one of those recent changes and to use that, one would have to build the DLL from the latest source code. I realize not everyone might be able to do this, so I'll try to make a release available soon.

**Comment by Harvey13** [comment]
Hello 
I tried to build from source but as I got many errors, I dropped.. 
Dll names didn't match.

⁣Envoyé par BlueMail ​

Le 21 mars 2017 02:34, à 02:34, Bugra Barin <notifications@github.com> a écrit:

**Comment by BugraB** [comment]
I just built the DLL and posted it. Please grab it from the latest Release (1.1.0.0) and give it a try.

**Comment by thomthom** [comment]
Hey @birsoyo - is this something we can set up Conan to pull in this repo and build it for both platform? Such that upon new release we have the recipe automated?

**Comment by birsoyo** [comment]
@thomthom  That's a good idea. I'll look into it.
