### ISSUE TITLE
Debugger does not open sketchup - hangs, force quit required

### ISSUE THREAD

**Issue by apj68** [SketchUp/sketchup-ruby-debugger#13]
I am trying to get the EP Fastener Plugin to work on my Sketchup 2017 running on OS X 10.11.6.  It opens only with a blank dialog window so I want to install the debugger to see if I can see any problems occurring.  

I downloaded `SURubyDebugger.dylib` (578756 bytes) and put it in `/Applications/SketchUp 2017/SketchUp.app/Contents/Frameworks` per the instructions.  When I run this:

    open -a /Applications/SketchUp\ 2015/SketchUp.app --args -rdebug "ide port=7000"

I get this:

    FSPathMakeRef(/Applications/SketchUp 2015/SketchUp.app) failed with error -43.

Any suggestions?

**Comment by BugraB** [comment]
You seem to have put the dylib inside 2017 but running 2015. Or is that a typo?

**Comment by apj68** [comment]
Rutrow. . . you're right, I copied and pasted from the instruction page, I do have 2017 installed and when I changed the path I was using to "open" things act differently.  Now it doesn't open it just bounces up and down in the tray for a while and when it stops bouncing there is no window, I just have to force quit it from the tray.

**Comment by BugraB** [comment]
If you launch the program in debugger mode, it'll wait for a debugger to be attached. Are you attaching one? If not, yes it will appear unresponsive.

**Comment by apj68** [comment]
D'oh!  Ok, sorry about that.  I was thinking a debugger would launch but now I see that it's only opening the port for a third-party debugger.  Thanks for talking me through it!

**Comment by BugraB** [comment]
Not a problem. If you simply need to see the errors, the built-in Ruby console might be enough to give you a clue.
