### ISSUE TITLE
VSCode workflow questions

### ISSUE THREAD

**Issue by thomthom** [SketchUp/sketchup-ruby-debugger#14]
I've been trying to set up VS Code with the debugger. So far I've been able to make a task to launch SketchUp in debug mode. And a debug config to connect to it. But I've not been able to put this into a single action.

## `tasks.json`:

```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "taskName": "Debug in SketchUp 2017",
      "type": "shell",
      "command": "ruby",
      "args": [
        "${workspaceFolder}/tools/debug.rb",
        "2017"
      ],
      "problemMatcher": []
    }
  ]
}
```

### `debug.rb`

```ruby
# Launcher script for starting SketchUp in Ruby Debug mode.
version = ARGV[0].to_i
port = ARGV[1] || '7000'

if RUBY_PLATFORM =~ /darwin/
  raise 'Mac support not implemented'
else
  program_files_32bit = ENV['ProgramFiles(x86)']
  program_files_64bit = ENV['ProgramW6432']

  # Look for 32bit or 64bit SketchUp in default installation directory.
  paths = [program_files_32bit, program_files_64bit].map { |program_files|
    sketchup_path = File.join(program_files, 'SketchUp', "SketchUp #{version}")
    sketchup = File.join(sketchup_path, 'SketchUp.exe')
    File.expand_path(sketchup)
  }
  sketchup = paths.find { |path| File.exist?(path) }

  raise "SketchUp #{version} not found." if sketchup.nil?

  command = %("#{sketchup}" -rdebug "ide port=#{port}")
  spawn(command)
end

```

## `launch.json`:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for rdebug-ide",
      "type": "Ruby",
      "request": "attach",
      // "preLaunchTask": "Debug in SketchUp 2017",
      "cwd": "${workspaceRoot}",
      "remoteHost": "127.0.0.1",
      "remotePort": "7000",
      "remoteWorkspaceRoot": "${workspaceRoot}"
    }
  ]
}
```

As can be seen from `launch.json` I tried to trigger the debug task in `preLaunchTask`. This will start SketchUp, and debugger appear to be running - but not connected.

When I manually test by starting VSCode Ruby debugging without having started SketchUp first I see this in the VSCode console:

`Debugger error: Client: Error: connect ECONNREFUSED 127.0.0.1:7000`

If I launch SketchUp after that the debugger isn't able to detect that and connect. I have to terminate the connection and initiate it again.

So it appear that my `preLaunchTask` isn't ready in time for the VSCode debugger when it wants to connect.

Is this an issue with the VSCode Ruby extension? Or something that can be addressed in the SketchUp debugger interface?

With RubyMine I have similar setup, Remote Ruby Debug with a pre-launch task that starts SketchUp. Any ideas?

**Comment by BugraBarin** [comment]
I think the problem is that debug.rb exits too quickly, before SketchUp launches in debug mode. So, preLaunchTask finishes and VSCode attempts to attach before SU is ready. I would try putting in a sleep for 5sec or so after the spawn call.

**Comment by thomthom** [comment]
So I take it that the difference between RubyMine and VSCode is that RubyMine will actually keep the connection alive and keep on trying to connect where as VSCode just gives up on first try?

**Comment by BugraBarin** [comment]
I don't know but that sounds plausible. We could find out since it's open source.
Did the sleep work?

**Comment by thomthom** [comment]
Yea - sleep for 5 seconds seems to work. So that seems to confirm that VSCode expect the Ruby process it connects to to already exist.
Kindof which the `sleep` wasn't necessary...

**Comment by BugraBarin** [comment]
You could probably get away with something smaller than 5 sec but yeah, would be nice not to need that in the first place.

**Comment by BugraBarin** [comment]
@thomthom Can this be closed?

**Comment by thomthom** [comment]
Yarp!
