### ISSUE TITLE
No support for debugging on OSX

### ISSUE THREAD

**Issue by marvingreenberg** [SketchUp/sketchup-ruby-debugger#15]
If this is simply a windows-only feature, the documentation should state that.  As is, the setup starts with "install a dll", suggesting this is windows only.  Presumably it would not be incredibly difficult to add support for OSX.

**Comment by thomthom** [comment]
Hi Marvin.

We have the debugger available for OSX - please refer to the [Instructions for Mac OS X](https://github.com/SketchUp/sketchup-ruby-debugger#instructions-for-mac-os-x) section in the README.

But not that the CURL command is out of date - referring to an older release for SU2015 so you'd have to adjust for whatever version of SU you are using.

Under [Releases](https://github.com/SketchUp/sketchup-ruby-debugger/releases) you'll find Windows and OSX downloads for each supported SketchUp version.

**Comment by marvingreenberg** [comment]
Thomas Thomassen wrote:
> Hi Marvin.
>
> We have the debugger available for OSX - please refer to the
> Instructions for Mac OS X
> <https://github.com/SketchUp/sketchup-ruby-debugger#instructions-for-mac-os-x>
> section in the README.
>
Doh!  Sorry for not scrolling down. :-)
