### ISSUE TITLE
SketchUp 2018 release

### ISSUE THREAD

**Issue by noelwarr** [SketchUp/sketchup-ruby-debugger#16]
There doesn't seem to be a ruby debugger for SketchUp 2018.

**Comment by thomthom** [comment]
The Ruby interpreter didn't change for SU2018. You can use the same as the one released for SU2017.

**Comment by BugraBarin** [comment]
I added a note in the release indicating as such.

**Comment by noelwarr** [comment]
Ok, thanks.  sorry for the mis-report

2018-02-02 14:39 GMT+01:00 Thomas Thomassen <notifications@github.com>:
