### ISSUE TITLE
2020?

### ISSUE THREAD

**Issue by kengey** [SketchUp/sketchup-ruby-debugger#27]
When can we expect a release for 2020?

**Comment by BugraBarin** [comment]
I expect the latest release will work in 2020? Is it not?

**Comment by kengey** [comment]
Sorry @BugraBarin , I did not try it out. I just noticed the last release here on github was named 2019 so I thought there was a 2020 release still to come. My mistake. It seems to work fine.

**Comment by thomthom** [comment]
We only need to update this when SketchUp ships with a new Major/minor version update which wouldn't be binary compatible.

**Comment by BugraBarin** [comment]
I updated the label on the release to reduce confusion.
Thanks Kenny!
