### ISSUE TITLE
Help! VSCode+Debug+Sketchup

### ISSUE THREAD

**Issue by season-x** [SketchUp/sketchup-ruby-debugger#28]
I use last sketchup-ruby-debugger (2019-2020) on win10.but ,there is no reaction and output in my sketchup .
I am using sketchup 2020,Could you help me ?What should be adjusted?

-------------launch.json:
```
"version": "0.2.0",
    "configurations": [
        {
            "cwd": "${workspaceRoot}",
            "name": "Listen for rdebug-ide",
            "type": "Ruby",
            "request": "attach",
            "remoteHost": "127.0.0.1",
            "remotePort": "7000",
            "remoteWorkspaceRoot": "${workspaceRoot}"
        }
    ]
```
-------------tasks.json:
```
 "version": "2.0.0",
    "tasks": [
        {
            "label": "Debug SketchUp 2020",
            "type": "shell",
            "windows": {
                "command": "&'C:/Program Files/SketchUp/SketchUp 2020/SketchUp.exe' -rdebug 'ide port=7000'"
            }
        }
    ]
```
--------------Main.rb:
```
puts "Hello World!"
```

**Comment by thomthom** [comment]
What are you steps when you try this?

You use the Task to start SketchUp in debug mode and once SU has started to attach the debugger?

And you have the debug DLL installed next to sketchup.exe?

**Comment by season-x** [comment]
I was missing a step,I should load " main.rb" in sketchup Ruby console.So I made it,thank you again.

**Comment by thomthom** [comment]
Ah, yea - the extension needs to be set up to be loaded.

The tutorials/examples repo include a description pf how you can set up your extension to load from external source (your git repo for instance): https://github.com/SketchUp/sketchup-ruby-api-tutorials#loading-directly-from-the-repository
