### ISSUE TITLE
Help!getMenu(menu, flags, x, y, view)

### ISSUE THREAD

**Issue by season-x** [SketchUp/sketchup-ruby-debugger#29]
I want to create "new" context menu,so I use "getmenu".but I  want it to coexist with "sketchup context menu".
#-----------------------------------------------------------------------
def getMenu(menu, flags, x, y, view)
    	menu.add_item('Move'){
        UI.messagebox "Move_Tool"
    	}
    	menu.add_item('Scale'){
    		UI.messagebox "Scale_Tool"
    	}
    end
#-------------------------------------------------------
![signe](https://user-images.githubusercontent.com/47172915/89723726-aa5f2600-da2c-11ea-9f63-505d22e80dd3.jpg)
#----------------------------------------------------------
I also try to use "Win32API",but I failed.Anybody know?

**Comment by thomthom** [comment]
It's not possible to create additional menus like that. With Ruby tools you only get the default one, or your custom one (via `getMenu`.

Btw, for how to questions it's better to use the forums: https://forums.sketchup.com/c/developers/12

This repository is for the debugger tool itself.

If you have bug reports of feature requests for the APIs you can use the dedicated issue tracker: https://github.com/SketchUp/api-issue-tracker
