### ISSUE TITLE
sketchup-ruby-debugger compiled in debug mode, not show LOG messages

### ISSUE THREAD

**Issue by brodao2** [SketchUp/sketchup-ruby-debugger#38]
Hi

I'm doing some experiments and compiled sketchup-ruby-debugger in debug mode.

Using the master branch causes crash in Sketchup.

I switched to the branch dev/ruby32 and the SU booted without problems, but I don't see any log messages.

From what I understand, it should appear in the ruby ​​console.

I'm using Sketchup 2023.

Any idea?

Thank you in advance

PS: Sorry my bad english.

**Comment by thomthom** [comment]
> Using the master branch causes crash in Sketchup.

You can't mix Debug build of the debugger with a Release build of SketchUp. Your best bet will be to use Release but to turn off optimization. (There are binary incombabilities between Debug and Release runtimes and ABI in C++)

**Comment by thomthom** [comment]
> I switched to the branch dev/ruby32 and the SU booted without problems, but I don't see any log messages.
> 
> From what I understand, it should appear in the ruby ​​console.

I'm not sure what kind of log messages you are referring to..?

**Comment by brodao2** [comment]
HI @thomthom 

This one example:
![image](https://github.com/SketchUp/sketchup-ruby-debugger/assets/114854608/41bf28dc-ea11-42f9-9301-3b08f8d361de)

The messages of LOG macro.

``#define LOG(msg) (SketchUp::RubyDebugger::Log::Write(LOG_CONTEXT, (msg)))``

**Comment by brodao2** [comment]
@thomthom 

Using the DLL provided and starting SU through VisualStudio, I can see the log messages.

Grateful.

**Comment by thomthom** [comment]
`LOG` is not being sent to the Ruby Console. On windows is to `OutputDebugString`:
https://github.com/SketchUp/sketchup-ruby-debugger/blob/main/DebugServer/Log.h#L69

Tools such as DebugView can list it: https://learn.microsoft.com/en-us/sysinternals/downloads/debugview
Though I think VS also displays the messages if it's attached as a debugger to SU.
