### ISSUE TITLE
Bug splats when keeping debug session open

### ISSUE THREAD

**Issue by gouldingken** [SketchUp/sketchup-ruby-debugger#6]
I just upgraded to SketchUp 2015 and although the debugger works exactly as before with 2014, SketchUp is crashing if I spend too long stepping through code.

**Comment by BugraB** [comment]
Hi. Do you see a BugSplat window coming up after the crash? If so, can you submit the crash? Please put your GitHub user name in there so I can find it.
Thanks!

**Comment by gouldingken** [comment]
This was happening repeatedly, but I have not been able to replicate since posting. If it happens again I will submit the BugSplat report with my username.

Thanks!
