### ISSUE TITLE
Close then open a new TCP connection?

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/sketchup-ruby-debugger#7]
Should it be possible to close the socket connection to the debug server, then open a new connection? 

Currently if I close the socket connection, I get the message `system:10054` from SketchUp in my debugger window. The debug server does not respond when I attempt to open a new connection.

Attached is a screen-shot of a simple session. 
- I start SketchUp with the debug server enabled `sketchup.exe -rdebug "ide"`
- I initialize a `TCPSocket`
- I send a `where` command. SketchUp acknowledges the command.
- I close the connection. SketchUp says `system:10054`
- I am not able to open a new connection.

NOTE - I have also seen the message `asio.misc:2` when disconnecting but I'm not sure how to reproduce one result over the other. 

![2016-03_376](https://cloud.githubusercontent.com/assets/137514/13904149/38ddc3ba-ee6d-11e5-8489-817a86b37166.png)

**Comment by BugraB** [comment]
Hi Jim,
Currently the server will wait for a connection initially but won't listen for a new connection if the client disconnects. This would be a nice feature to implement.

**Comment by jimfoltz** [comment]
Thanks for the reply, @BugraB . 

I ask this because I am starting to like [vscode](https://code.visualstudio.com/) and the [vscode/ruby](https://github.com/rebornix/vscode-ruby) extension for writing SketchUp extensions - vscode has nice git and debugger support, but vscode/ruby does not quite play well with the SketchUp debug server. I'd like to improve that.

**Comment by BugraB** [comment]
I really like vscode too and believe it or not I thought about this very thing the other day. I'd love to work on that but there are just too many projects and too little time in the day :-)

**Comment by jimfoltz** [comment]
Just wanted to say thanks @seraku24 for this update. I compiled it last evening using g VS3015 Express and after having to make one small change was able successfully use this version in VSCode.

**Comment by thomthom** [comment]
@jimfoltz what was the change you had to do?

**Comment by jimfoltz** [comment]
It was adding the "public" keyword at RDIP.cpp line 34. I see it has already been added by @BugraB.

https://github.com/SketchUp/sketchup-ruby-debugger/blob/master/DebugServer/UI/RDIP/RDIP.cpp#L34
